### ISSUE TITLE
Error message/Retrieving game image

### ISSUE THREAD

**Issue by darias08** [nunogois/game-search-expo#4]
Hello,  sorry to bother you again :( 

I have some question I want to ask you, 

1.) I wanted to play around with your app and I have been getting an error message when I launch the app from expo. Here's an image link of what the error is showing.
https://drive.google.com/file/d/1qxXay-IjTiO8Qb-oNX53cr1bdeTgZSTX/view?usp=sharing

2.) So good news I was able to pull the list of games from IGDB but the issue I am only having so far is retrieving the game images. I am seeing in line 16 at https://github.com/nunogois/game-search-expo/blob/c480a336c1335effdf1c3daebb0199d7323461f7/components/GameItem.tsx#L16

You only specify game.image which I am confused as to how you would use that to get the cover art? I am seeing on their IGDB website https://api-docs.igdb.com/#cover you would have to call image_id or url to get the image I am guessing. But when I try to invoke one of those two fields nothing happens or displays. However, I am able to display that name of the game titles, but I am confused as to how I can display the list of game images. Do you know how I can make this work?

**Comment by nunogois** [comment]
Hey @darias08,

1) This app is not being maintained at the moment (last commit was early July 2021), and it seems like Expo is expecting the app to be running on a more up-to-date SDK version. I'm not planning for this upgrade anytime soon, but if anyone wants to contribute with a PR they're more than welcome. Maybe it could be a good exercise for you to learn more about how this app works and develop your own afterwards.

2) You can see how the image is being mapped from the cover url here:
https://github.com/nunogois/game-search-expo/blob/c480a336c1335effdf1c3daebb0199d7323461f7/hooks/Games.ts#L4-L52

Line 12 passes a processed URL as the 3rd parameter of `Game`, which as you can see here, is the image:
https://github.com/nunogois/game-search-expo/blob/c480a336c1335effdf1c3daebb0199d7323461f7/models/game.ts#L13-L60
